# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inspform.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_InspectionDialog(object):
    def setupUi(self, InspectionDialog):
        InspectionDialog.setObjectName("InspectionDialog")
        InspectionDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        InspectionDialog.resize(758, 662)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(InspectionDialog.sizePolicy().hasHeightForWidth())
        InspectionDialog.setSizePolicy(sizePolicy)
        InspectionDialog.setSizeIncrement(QtCore.QSize(0, 3))
        InspectionDialog.setBaseSize(QtCore.QSize(0, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        InspectionDialog.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/Icons/work/006.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        InspectionDialog.setWindowIcon(icon)
        InspectionDialog.setModal(True)
        self.gridLayout_2 = QtWidgets.QGridLayout(InspectionDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(InspectionDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tabInitiate = QtWidgets.QWidget()
        self.tabInitiate.setObjectName("tabInitiate")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tabInitiate)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.grdTypeObject = QtWidgets.QGridLayout()
        self.grdTypeObject.setObjectName("grdTypeObject")
        self.grpObject = QtWidgets.QGroupBox(self.tabInitiate)
        self.grpObject.setObjectName("grpObject")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.grpObject)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.lblObjectName = QtWidgets.QLabel(self.grpObject)
        self.lblObjectName.setObjectName("lblObjectName")
        self.gridLayout_9.addWidget(self.lblObjectName, 0, 0, 1, 1)
        self.btnObject = QtWidgets.QPushButton(self.grpObject)
        self.btnObject.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ico/Icons/finance/014.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnObject.setIcon(icon1)
        self.btnObject.setObjectName("btnObject")
        self.gridLayout_9.addWidget(self.btnObject, 0, 2, 1, 1)
        self.lblObjectCode = QtWidgets.QLabel(self.grpObject)
        self.lblObjectCode.setObjectName("lblObjectCode")
        self.gridLayout_9.addWidget(self.lblObjectCode, 1, 0, 1, 1)
        self.fldObjectCode = QtWidgets.QLineEdit(self.grpObject)
        self.fldObjectCode.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.fldObjectCode.setMaxLength(10)
        self.fldObjectCode.setReadOnly(False)
        self.fldObjectCode.setClearButtonEnabled(False)
        self.fldObjectCode.setObjectName("fldObjectCode")
        self.gridLayout_9.addWidget(self.fldObjectCode, 1, 1, 1, 1)
        self.lblObjectAddress = QtWidgets.QLabel(self.grpObject)
        self.lblObjectAddress.setObjectName("lblObjectAddress")
        self.gridLayout_9.addWidget(self.lblObjectAddress, 2, 0, 1, 1)
        self.fldObjectAddress = QtWidgets.QLineEdit(self.grpObject)
        self.fldObjectAddress.setReadOnly(False)
        self.fldObjectAddress.setObjectName("fldObjectAddress")
        self.gridLayout_9.addWidget(self.fldObjectAddress, 2, 1, 1, 1)
        self.comboBoxObjectName = QtWidgets.QComboBox(self.grpObject)
        self.comboBoxObjectName.setInputMethodHints(QtCore.Qt.ImhNoTextHandles)
        self.comboBoxObjectName.setEditable(True)
        self.comboBoxObjectName.setInsertPolicy(QtWidgets.QComboBox.InsertAfterCurrent)
        self.comboBoxObjectName.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.comboBoxObjectName.setModelColumn(0)
        self.comboBoxObjectName.setObjectName("comboBoxObjectName")
        self.gridLayout_9.addWidget(self.comboBoxObjectName, 0, 1, 1, 1)
        self.grdTypeObject.addWidget(self.grpObject, 0, 1, 1, 1)
        self.grpType = QtWidgets.QGroupBox(self.tabInitiate)
        self.grpType.setObjectName("grpType")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.grpType)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lblType1 = QtWidgets.QLabel(self.grpType)
        self.lblType1.setObjectName("lblType1")
        self.gridLayout_7.addWidget(self.lblType1, 0, 0, 1, 1)
        self.cmbType1 = QtWidgets.QComboBox(self.grpType)
        self.cmbType1.setObjectName("cmbType1")
        self.cmbType1.addItem("")
        self.cmbType1.addItem("")
        self.gridLayout_7.addWidget(self.cmbType1, 0, 1, 1, 1)
        self.lblType2 = QtWidgets.QLabel(self.grpType)
        self.lblType2.setObjectName("lblType2")
        self.gridLayout_7.addWidget(self.lblType2, 1, 0, 1, 1)
        self.cmbType2 = QtWidgets.QComboBox(self.grpType)
        self.cmbType2.setObjectName("cmbType2")
        self.cmbType2.addItem("")
        self.cmbType2.addItem("")
        self.cmbType2.addItem("")
        self.gridLayout_7.addWidget(self.cmbType2, 1, 1, 1, 1)
        self.lblType3 = QtWidgets.QLabel(self.grpType)
        self.lblType3.setObjectName("lblType3")
        self.gridLayout_7.addWidget(self.lblType3, 2, 0, 1, 1)
        self.cmbType3 = QtWidgets.QComboBox(self.grpType)
        self.cmbType3.setObjectName("cmbType3")
        self.cmbType3.addItem("")
        self.cmbType3.addItem("")
        self.gridLayout_7.addWidget(self.cmbType3, 2, 1, 1, 1)
        self.btnPlan = QtWidgets.QPushButton(self.grpType)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPlan.sizePolicy().hasHeightForWidth())
        self.btnPlan.setSizePolicy(sizePolicy)
        self.btnPlan.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ico/Icons/education/025.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPlan.setIcon(icon2)
        self.btnPlan.setObjectName("btnPlan")
        self.gridLayout_7.addWidget(self.btnPlan, 1, 2, 1, 1)
        self.grdTypeObject.addWidget(self.grpType, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.grdTypeObject, 0, 0, 1, 1)
        self.grdBasis = QtWidgets.QGridLayout()
        self.grdBasis.setObjectName("grdBasis")
        self.grpBasis = QtWidgets.QGroupBox(self.tabInitiate)
        self.grpBasis.setObjectName("grpBasis")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.grpBasis)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.frameBasisControl = QtWidgets.QFrame(self.grpBasis)
        self.frameBasisControl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBasisControl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBasisControl.setObjectName("frameBasisControl")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frameBasisControl)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.btnBasisView = QtWidgets.QPushButton(self.frameBasisControl)
        self.btnBasisView.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/ico/Icons/basic/064.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBasisView.setIcon(icon3)
        self.btnBasisView.setObjectName("btnBasisView")
        self.gridLayout_5.addWidget(self.btnBasisView, 1, 0, 1, 1)
        self.btnBasisAdd = QtWidgets.QPushButton(self.frameBasisControl)
        self.btnBasisAdd.setAccessibleDescription("")
        self.btnBasisAdd.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/ico/Icons/basic/058.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBasisAdd.setIcon(icon4)
        self.btnBasisAdd.setObjectName("btnBasisAdd")
        self.gridLayout_5.addWidget(self.btnBasisAdd, 0, 0, 1, 1)
        self.btnBasisDelete = QtWidgets.QPushButton(self.frameBasisControl)
        self.btnBasisDelete.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/ico/Icons/basic/059.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBasisDelete.setIcon(icon5)
        self.btnBasisDelete.setObjectName("btnBasisDelete")
        self.gridLayout_5.addWidget(self.btnBasisDelete, 4, 0, 1, 1)
        self.btnBasisDeleteAll = QtWidgets.QPushButton(self.frameBasisControl)
        self.btnBasisDeleteAll.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/ico/Icons/basic/060.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBasisDeleteAll.setIcon(icon6)
        self.btnBasisDeleteAll.setObjectName("btnBasisDeleteAll")
        self.gridLayout_5.addWidget(self.btnBasisDeleteAll, 5, 0, 1, 1)
        self.btnBasisEdit = QtWidgets.QPushButton(self.frameBasisControl)
        self.btnBasisEdit.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/ico/Icons/education/027.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBasisEdit.setIcon(icon7)
        self.btnBasisEdit.setObjectName("btnBasisEdit")
        self.gridLayout_5.addWidget(self.btnBasisEdit, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 3, 0, 1, 1)
        self.gridLayout_11.addWidget(self.frameBasisControl, 1, 1, 1, 1)
        self.tblBasis = QtWidgets.QTableWidget(self.grpBasis)
        self.tblBasis.setAutoFillBackground(False)
        self.tblBasis.setMidLineWidth(0)
        self.tblBasis.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tblBasis.setAlternatingRowColors(True)
        self.tblBasis.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblBasis.setTextElideMode(QtCore.Qt.ElideRight)
        self.tblBasis.setCornerButtonEnabled(False)
        self.tblBasis.setRowCount(0)
        self.tblBasis.setObjectName("tblBasis")
        self.tblBasis.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(85, 170, 255))
        self.tblBasis.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(85, 170, 255))
        self.tblBasis.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(85, 170, 255))
        self.tblBasis.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(85, 170, 255))
        self.tblBasis.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(85, 170, 255))
        self.tblBasis.setHorizontalHeaderItem(4, item)
        self.tblBasis.horizontalHeader().setVisible(True)
        self.tblBasis.horizontalHeader().setCascadingSectionResizes(True)
        self.tblBasis.horizontalHeader().setDefaultSectionSize(120)
        self.tblBasis.horizontalHeader().setHighlightSections(True)
        self.tblBasis.horizontalHeader().setMinimumSectionSize(50)
        self.tblBasis.horizontalHeader().setStretchLastSection(False)
        self.tblBasis.verticalHeader().setVisible(False)
        self.tblBasis.verticalHeader().setCascadingSectionResizes(True)
        self.gridLayout_11.addWidget(self.tblBasis, 1, 0, 1, 1)
        self.grdBasis.addWidget(self.grpBasis, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.grdBasis, 1, 0, 1, 1)
        self.grdPurpose = QtWidgets.QGridLayout()
        self.grdPurpose.setObjectName("grdPurpose")
        self.grpPurpose = QtWidgets.QGroupBox(self.tabInitiate)
        self.grpPurpose.setObjectName("grpPurpose")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.grpPurpose)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.fldPurpose = QtWidgets.QPlainTextEdit(self.grpPurpose)
        self.fldPurpose.setObjectName("fldPurpose")
        self.gridLayout_12.addWidget(self.fldPurpose, 0, 0, 1, 1)
        self.grdPurpose.addWidget(self.grpPurpose, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.grdPurpose, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tabInitiate, "")
        self.tabDates = QtWidgets.QWidget()
        self.tabDates.setObjectName("tabDates")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tabDates)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.grpDates = QtWidgets.QGroupBox(self.tabDates)
        self.grpDates.setFlat(False)
        self.grpDates.setObjectName("grpDates")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.grpDates)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lblInspectionFrom = QtWidgets.QLabel(self.grpDates)
        self.lblInspectionFrom.setObjectName("lblInspectionFrom")
        self.gridLayout_3.addWidget(self.lblInspectionFrom, 0, 0, 1, 1)
        self.fldInspectionFrom = QtWidgets.QDateEdit(self.grpDates)
        self.fldInspectionFrom.setCalendarPopup(True)
        self.fldInspectionFrom.setDate(QtCore.QDate(2019, 1, 1))
        self.fldInspectionFrom.setObjectName("fldInspectionFrom")
        self.gridLayout_3.addWidget(self.fldInspectionFrom, 0, 1, 1, 1)
        self.lblInspectionTo = QtWidgets.QLabel(self.grpDates)
        self.lblInspectionTo.setObjectName("lblInspectionTo")
        self.gridLayout_3.addWidget(self.lblInspectionTo, 1, 0, 1, 1)
        self.fldInspectionTo = QtWidgets.QDateEdit(self.grpDates)
        self.fldInspectionTo.setCalendarPopup(True)
        self.fldInspectionTo.setDate(QtCore.QDate(2019, 1, 1))
        self.fldInspectionTo.setObjectName("fldInspectionTo")
        self.gridLayout_3.addWidget(self.fldInspectionTo, 1, 1, 1, 1)
        self.lblControlDate = QtWidgets.QLabel(self.grpDates)
        self.lblControlDate.setObjectName("lblControlDate")
        self.gridLayout_3.addWidget(self.lblControlDate, 2, 0, 1, 1)
        self.fldControlDate = QtWidgets.QDateEdit(self.grpDates)
        self.fldControlDate.setCalendarPopup(True)
        self.fldControlDate.setDate(QtCore.QDate(2019, 1, 1))
        self.fldControlDate.setObjectName("fldControlDate")
        self.gridLayout_3.addWidget(self.fldControlDate, 2, 1, 1, 1)
        self.lblPeriodFrom = QtWidgets.QLabel(self.grpDates)
        self.lblPeriodFrom.setObjectName("lblPeriodFrom")
        self.gridLayout_3.addWidget(self.lblPeriodFrom, 0, 3, 1, 1)
        self.fldPeriodFrom = QtWidgets.QDateEdit(self.grpDates)
        self.fldPeriodFrom.setCalendarPopup(True)
        self.fldPeriodFrom.setDate(QtCore.QDate(2019, 1, 1))
        self.fldPeriodFrom.setObjectName("fldPeriodFrom")
        self.gridLayout_3.addWidget(self.fldPeriodFrom, 0, 4, 1, 1)
        self.fldPeriodTo = QtWidgets.QDateEdit(self.grpDates)
        self.fldPeriodTo.setCalendarPopup(True)
        self.fldPeriodTo.setDate(QtCore.QDate(2019, 1, 1))
        self.fldPeriodTo.setObjectName("fldPeriodTo")
        self.gridLayout_3.addWidget(self.fldPeriodTo, 1, 4, 1, 1)
        self.lblPeriodTo = QtWidgets.QLabel(self.grpDates)
        self.lblPeriodTo.setObjectName("lblPeriodTo")
        self.gridLayout_3.addWidget(self.lblPeriodTo, 1, 3, 1, 1)
        self.fldNewControlDate = QtWidgets.QDateEdit(self.grpDates)
        self.fldNewControlDate.setWrapping(False)
        self.fldNewControlDate.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.fldNewControlDate.setProperty("showGroupSeparator", False)
        self.fldNewControlDate.setCalendarPopup(True)
        self.fldNewControlDate.setDate(QtCore.QDate(2019, 1, 1))
        self.fldNewControlDate.setObjectName("fldNewControlDate")
        self.gridLayout_3.addWidget(self.fldNewControlDate, 2, 4, 1, 1)
        self.lblNewControlDate = QtWidgets.QLabel(self.grpDates)
        self.lblNewControlDate.setObjectName("lblNewControlDate")
        self.gridLayout_3.addWidget(self.lblNewControlDate, 2, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 5, 1, 1)
        self.gridLayout_8.addWidget(self.grpDates, 0, 0, 1, 1)
        self.grdCalendar = QtWidgets.QGridLayout()
        self.grdCalendar.setObjectName("grdCalendar")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.tabDates)
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setObjectName("calendarWidget")
        self.grdCalendar.addWidget(self.calendarWidget, 0, 1, 1, 1)
        self.grpOptions = QtWidgets.QGroupBox(self.tabDates)
        self.grpOptions.setObjectName("grpOptions")
        self.formLayout = QtWidgets.QFormLayout(self.grpOptions)
        self.formLayout.setObjectName("formLayout")
        self.chkDates = QtWidgets.QCheckBox(self.grpOptions)
        self.chkDates.setTristate(False)
        self.chkDates.setObjectName("chkDates")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.chkDates)
        self.chkPeriod = QtWidgets.QCheckBox(self.grpOptions)
        self.chkPeriod.setObjectName("chkPeriod")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.chkPeriod)
        self.chkControlDate = QtWidgets.QCheckBox(self.grpOptions)
        self.chkControlDate.setObjectName("chkControlDate")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.chkControlDate)
        self.grdCalendar.addWidget(self.grpOptions, 0, 2, 1, 1)
        self.gridLayout_8.addLayout(self.grdCalendar, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabDates, "")
        self.tabGroup = QtWidgets.QWidget()
        self.tabGroup.setObjectName("tabGroup")
        self.gridLayout = QtWidgets.QGridLayout(self.tabGroup)
        self.gridLayout.setObjectName("gridLayout")
        self.grpGroup = QtWidgets.QGroupBox(self.tabGroup)
        self.grpGroup.setObjectName("grpGroup")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.grpGroup)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.tblGroup = QtWidgets.QTableWidget(self.grpGroup)
        self.tblGroup.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tblGroup.setAlternatingRowColors(True)
        self.tblGroup.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblGroup.setCornerButtonEnabled(False)
        self.tblGroup.setRowCount(20)
        self.tblGroup.setObjectName("tblGroup")
        self.tblGroup.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(85, 170, 255))
        self.tblGroup.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(85, 170, 255))
        self.tblGroup.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(85, 170, 255))
        self.tblGroup.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(85, 170, 255))
        self.tblGroup.setHorizontalHeaderItem(3, item)
        self.tblGroup.horizontalHeader().setCascadingSectionResizes(True)
        self.tblGroup.horizontalHeader().setDefaultSectionSize(170)
        self.tblGroup.horizontalHeader().setStretchLastSection(True)
        self.tblGroup.verticalHeader().setVisible(False)
        self.gridLayout_13.addWidget(self.tblGroup, 1, 0, 1, 1)
        self.frameGroupControl = QtWidgets.QFrame(self.grpGroup)
        self.frameGroupControl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameGroupControl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameGroupControl.setObjectName("frameGroupControl")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frameGroupControl)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.btnGroupDeleteAll = QtWidgets.QPushButton(self.frameGroupControl)
        self.btnGroupDeleteAll.setText("")
        self.btnGroupDeleteAll.setIcon(icon6)
        self.btnGroupDeleteAll.setObjectName("btnGroupDeleteAll")
        self.gridLayout_10.addWidget(self.btnGroupDeleteAll, 0, 6, 1, 1)
        self.btnGroupDelete = QtWidgets.QPushButton(self.frameGroupControl)
        self.btnGroupDelete.setText("")
        self.btnGroupDelete.setIcon(icon5)
        self.btnGroupDelete.setObjectName("btnGroupDelete")
        self.gridLayout_10.addWidget(self.btnGroupDelete, 0, 5, 1, 1)
        self.btnGroupEdit = QtWidgets.QPushButton(self.frameGroupControl)
        self.btnGroupEdit.setText("")
        self.btnGroupEdit.setIcon(icon7)
        self.btnGroupEdit.setObjectName("btnGroupEdit")
        self.gridLayout_10.addWidget(self.btnGroupEdit, 0, 3, 1, 1)
        self.btnGroupView = QtWidgets.QPushButton(self.frameGroupControl)
        self.btnGroupView.setText("")
        self.btnGroupView.setIcon(icon3)
        self.btnGroupView.setObjectName("btnGroupView")
        self.gridLayout_10.addWidget(self.btnGroupView, 0, 2, 1, 1)
        self.btnGroupAdd = QtWidgets.QPushButton(self.frameGroupControl)
        self.btnGroupAdd.setText("")
        self.btnGroupAdd.setIcon(icon4)
        self.btnGroupAdd.setObjectName("btnGroupAdd")
        self.gridLayout_10.addWidget(self.btnGroupAdd, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem3, 0, 4, 1, 1)
        self.gridLayout_13.addWidget(self.frameGroupControl, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.grpGroup, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabGroup, "")
        self.tabConduct = QtWidgets.QWidget()
        self.tabConduct.setObjectName("tabConduct")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabConduct)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.grpStopContinue = QtWidgets.QGroupBox(self.tabConduct)
        self.grpStopContinue.setCheckable(True)
        self.grpStopContinue.setChecked(False)
        self.grpStopContinue.setObjectName("grpStopContinue")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.grpStopContinue)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.tblStopContinue = QtWidgets.QTableWidget(self.grpStopContinue)
        self.tblStopContinue.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tblStopContinue.setAlternatingRowColors(True)
        self.tblStopContinue.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblStopContinue.setRowCount(10)
        self.tblStopContinue.setObjectName("tblStopContinue")
        self.tblStopContinue.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(85, 170, 255))
        self.tblStopContinue.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(85, 170, 255))
        self.tblStopContinue.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(85, 170, 255))
        self.tblStopContinue.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(85, 170, 255))
        self.tblStopContinue.setHorizontalHeaderItem(3, item)
        self.tblStopContinue.horizontalHeader().setDefaultSectionSize(100)
        self.tblStopContinue.horizontalHeader().setSortIndicatorShown(True)
        self.tblStopContinue.horizontalHeader().setStretchLastSection(True)
        self.tblStopContinue.verticalHeader().setVisible(False)
        self.gridLayout_14.addWidget(self.tblStopContinue, 0, 0, 1, 1)
        self.frameStopControl = QtWidgets.QFrame(self.grpStopContinue)
        self.frameStopControl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameStopControl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameStopControl.setObjectName("frameStopControl")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.frameStopControl)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.btnStopAdd = QtWidgets.QPushButton(self.frameStopControl)
        self.btnStopAdd.setText("")
        self.btnStopAdd.setIcon(icon4)
        self.btnStopAdd.setObjectName("btnStopAdd")
        self.gridLayout_25.addWidget(self.btnStopAdd, 0, 0, 1, 1)
        self.btnStopView = QtWidgets.QPushButton(self.frameStopControl)
        self.btnStopView.setText("")
        self.btnStopView.setIcon(icon3)
        self.btnStopView.setObjectName("btnStopView")
        self.gridLayout_25.addWidget(self.btnStopView, 1, 0, 1, 1)
        self.btnStopEdit = QtWidgets.QPushButton(self.frameStopControl)
        self.btnStopEdit.setText("")
        self.btnStopEdit.setIcon(icon7)
        self.btnStopEdit.setObjectName("btnStopEdit")
        self.gridLayout_25.addWidget(self.btnStopEdit, 2, 0, 1, 1)
        self.btnStopDelete = QtWidgets.QPushButton(self.frameStopControl)
        self.btnStopDelete.setText("")
        self.btnStopDelete.setIcon(icon5)
        self.btnStopDelete.setObjectName("btnStopDelete")
        self.gridLayout_25.addWidget(self.btnStopDelete, 4, 0, 1, 1)
        self.btnStopDeleteAll = QtWidgets.QPushButton(self.frameStopControl)
        self.btnStopDeleteAll.setText("")
        self.btnStopDeleteAll.setIcon(icon6)
        self.btnStopDeleteAll.setObjectName("btnStopDeleteAll")
        self.gridLayout_25.addWidget(self.btnStopDeleteAll, 5, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_25.addItem(spacerItem4, 3, 0, 1, 1)
        self.gridLayout_14.addWidget(self.frameStopControl, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.grpStopContinue)
        self.grpRefuse = QtWidgets.QGroupBox(self.tabConduct)
        self.grpRefuse.setCheckable(True)
        self.grpRefuse.setChecked(False)
        self.grpRefuse.setObjectName("grpRefuse")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.grpRefuse)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.tblRefuse = QtWidgets.QTableWidget(self.grpRefuse)
        self.tblRefuse.setAlternatingRowColors(True)
        self.tblRefuse.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblRefuse.setRowCount(10)
        self.tblRefuse.setObjectName("tblRefuse")
        self.tblRefuse.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(85, 170, 255))
        self.tblRefuse.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(85, 170, 255))
        self.tblRefuse.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(85, 170, 255))
        self.tblRefuse.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(85, 170, 255))
        self.tblRefuse.setHorizontalHeaderItem(3, item)
        self.tblRefuse.horizontalHeader().setSortIndicatorShown(True)
        self.tblRefuse.horizontalHeader().setStretchLastSection(True)
        self.tblRefuse.verticalHeader().setVisible(False)
        self.gridLayout_15.addWidget(self.tblRefuse, 0, 0, 1, 1)
        self.frameRefuseControl = QtWidgets.QFrame(self.grpRefuse)
        self.frameRefuseControl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameRefuseControl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameRefuseControl.setObjectName("frameRefuseControl")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.frameRefuseControl)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.btnRefuseAdd = QtWidgets.QPushButton(self.frameRefuseControl)
        self.btnRefuseAdd.setText("")
        self.btnRefuseAdd.setIcon(icon4)
        self.btnRefuseAdd.setObjectName("btnRefuseAdd")
        self.gridLayout_26.addWidget(self.btnRefuseAdd, 0, 0, 1, 1)
        self.btnRefuseView = QtWidgets.QPushButton(self.frameRefuseControl)
        self.btnRefuseView.setText("")
        self.btnRefuseView.setIcon(icon3)
        self.btnRefuseView.setObjectName("btnRefuseView")
        self.gridLayout_26.addWidget(self.btnRefuseView, 1, 0, 1, 1)
        self.btnRefuseEdit = QtWidgets.QPushButton(self.frameRefuseControl)
        self.btnRefuseEdit.setText("")
        self.btnRefuseEdit.setIcon(icon7)
        self.btnRefuseEdit.setObjectName("btnRefuseEdit")
        self.gridLayout_26.addWidget(self.btnRefuseEdit, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 65, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_26.addItem(spacerItem5, 3, 0, 1, 1)
        self.btnRefuseDelete = QtWidgets.QPushButton(self.frameRefuseControl)
        self.btnRefuseDelete.setText("")
        self.btnRefuseDelete.setIcon(icon5)
        self.btnRefuseDelete.setObjectName("btnRefuseDelete")
        self.gridLayout_26.addWidget(self.btnRefuseDelete, 4, 0, 1, 1)
        self.btnRefuseDeleteAll = QtWidgets.QPushButton(self.frameRefuseControl)
        self.btnRefuseDeleteAll.setText("")
        self.btnRefuseDeleteAll.setIcon(icon6)
        self.btnRefuseDeleteAll.setObjectName("btnRefuseDeleteAll")
        self.gridLayout_26.addWidget(self.btnRefuseDeleteAll, 5, 0, 1, 1)
        self.gridLayout_15.addWidget(self.frameRefuseControl, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.grpRefuse)
        self.tabWidget.addTab(self.tabConduct, "")
        self.tabFinish = QtWidgets.QWidget()
        self.tabFinish.setObjectName("tabFinish")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabFinish)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.grpResultDocs = QtWidgets.QGroupBox(self.tabFinish)
        self.grpResultDocs.setCheckable(True)
        self.grpResultDocs.setChecked(False)
        self.grpResultDocs.setObjectName("grpResultDocs")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.grpResultDocs)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.tblResultDocs = QtWidgets.QTableWidget(self.grpResultDocs)
        self.tblResultDocs.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tblResultDocs.setAlternatingRowColors(True)
        self.tblResultDocs.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblResultDocs.setRowCount(10)
        self.tblResultDocs.setObjectName("tblResultDocs")
        self.tblResultDocs.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(85, 170, 255))
        self.tblResultDocs.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(85, 170, 255))
        self.tblResultDocs.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(85, 170, 255))
        self.tblResultDocs.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(85, 170, 255))
        self.tblResultDocs.setHorizontalHeaderItem(3, item)
        self.tblResultDocs.horizontalHeader().setDefaultSectionSize(200)
        self.tblResultDocs.horizontalHeader().setSortIndicatorShown(True)
        self.tblResultDocs.horizontalHeader().setStretchLastSection(True)
        self.tblResultDocs.verticalHeader().setVisible(False)
        self.gridLayout_18.addWidget(self.tblResultDocs, 1, 0, 1, 1)
        self.frameResultControl = QtWidgets.QFrame(self.grpResultDocs)
        self.frameResultControl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameResultControl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameResultControl.setObjectName("frameResultControl")
        self.gridLayout_51 = QtWidgets.QGridLayout(self.frameResultControl)
        self.gridLayout_51.setObjectName("gridLayout_51")
        self.btnResultDeleteAll = QtWidgets.QPushButton(self.frameResultControl)
        self.btnResultDeleteAll.setText("")
        self.btnResultDeleteAll.setIcon(icon6)
        self.btnResultDeleteAll.setObjectName("btnResultDeleteAll")
        self.gridLayout_51.addWidget(self.btnResultDeleteAll, 0, 5, 1, 1)
        self.btnResultView = QtWidgets.QPushButton(self.frameResultControl)
        self.btnResultView.setText("")
        self.btnResultView.setIcon(icon3)
        self.btnResultView.setObjectName("btnResultView")
        self.gridLayout_51.addWidget(self.btnResultView, 0, 1, 1, 1)
        self.btnResultDelete = QtWidgets.QPushButton(self.frameResultControl)
        self.btnResultDelete.setText("")
        self.btnResultDelete.setIcon(icon5)
        self.btnResultDelete.setObjectName("btnResultDelete")
        self.gridLayout_51.addWidget(self.btnResultDelete, 0, 4, 1, 1)
        self.btnResultEdit = QtWidgets.QPushButton(self.frameResultControl)
        self.btnResultEdit.setText("")
        self.btnResultEdit.setIcon(icon7)
        self.btnResultEdit.setObjectName("btnResultEdit")
        self.gridLayout_51.addWidget(self.btnResultEdit, 0, 2, 1, 1)
        self.btnResultAdd = QtWidgets.QPushButton(self.frameResultControl)
        self.btnResultAdd.setText("")
        self.btnResultAdd.setIcon(icon4)
        self.btnResultAdd.setObjectName("btnResultAdd")
        self.gridLayout_51.addWidget(self.btnResultAdd, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_51.addItem(spacerItem6, 0, 3, 1, 1)
        self.gridLayout_18.addWidget(self.frameResultControl, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.grpResultDocs)
        self.grpEnforcement = QtWidgets.QGroupBox(self.tabFinish)
        self.grpEnforcement.setObjectName("grpEnforcement")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.grpEnforcement)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.chkEnforcement = QtWidgets.QCheckBox(self.grpEnforcement)
        self.chkEnforcement.setObjectName("chkEnforcement")
        self.gridLayout_17.addWidget(self.chkEnforcement, 0, 0, 1, 1)
        self.chkInternalSecurity = QtWidgets.QCheckBox(self.grpEnforcement)
        self.chkInternalSecurity.setObjectName("chkInternalSecurity")
        self.gridLayout_17.addWidget(self.chkInternalSecurity, 1, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.grpEnforcement)
        self.frmFinish = QtWidgets.QFrame(self.tabFinish)
        self.frmFinish.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmFinish.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmFinish.setObjectName("frmFinish")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frmFinish)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.chkFinish = QtWidgets.QCheckBox(self.frmFinish)
        self.chkFinish.setObjectName("chkFinish")
        self.gridLayout_16.addWidget(self.chkFinish, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.frmFinish)
        self.tabWidget.addTab(self.tabFinish, "")
        self.tabViolations = QtWidgets.QWidget()
        self.tabViolations.setObjectName("tabViolations")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabViolations)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.grpViolations = QtWidgets.QGroupBox(self.tabViolations)
        self.grpViolations.setCheckable(True)
        self.grpViolations.setChecked(False)
        self.grpViolations.setObjectName("grpViolations")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.grpViolations)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.tblViolations = QtWidgets.QTableWidget(self.grpViolations)
        self.tblViolations.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tblViolations.setAlternatingRowColors(True)
        self.tblViolations.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblViolations.setRowCount(20)
        self.tblViolations.setObjectName("tblViolations")
        self.tblViolations.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(85, 170, 255))
        self.tblViolations.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(85, 170, 255))
        self.tblViolations.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(85, 170, 255))
        self.tblViolations.setHorizontalHeaderItem(2, item)
        self.tblViolations.horizontalHeader().setDefaultSectionSize(120)
        self.tblViolations.horizontalHeader().setSortIndicatorShown(True)
        self.tblViolations.horizontalHeader().setStretchLastSection(True)
        self.tblViolations.verticalHeader().setVisible(False)
        self.gridLayout_20.addWidget(self.tblViolations, 1, 0, 1, 1)
        self.frameViolationControl = QtWidgets.QFrame(self.grpViolations)
        self.frameViolationControl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameViolationControl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameViolationControl.setObjectName("frameViolationControl")
        self.gridLayout_52 = QtWidgets.QGridLayout(self.frameViolationControl)
        self.gridLayout_52.setObjectName("gridLayout_52")
        self.btnViolationAdd = QtWidgets.QPushButton(self.frameViolationControl)
        self.btnViolationAdd.setText("")
        self.btnViolationAdd.setIcon(icon4)
        self.btnViolationAdd.setObjectName("btnViolationAdd")
        self.gridLayout_52.addWidget(self.btnViolationAdd, 0, 0, 1, 1)
        self.btnViolationEdit = QtWidgets.QPushButton(self.frameViolationControl)
        self.btnViolationEdit.setText("")
        self.btnViolationEdit.setIcon(icon7)
        self.btnViolationEdit.setObjectName("btnViolationEdit")
        self.gridLayout_52.addWidget(self.btnViolationEdit, 0, 2, 1, 1)
        self.btnViolationView = QtWidgets.QPushButton(self.frameViolationControl)
        self.btnViolationView.setText("")
        self.btnViolationView.setIcon(icon3)
        self.btnViolationView.setObjectName("btnViolationView")
        self.gridLayout_52.addWidget(self.btnViolationView, 0, 1, 1, 1)
        self.btnViolationDeleteAll = QtWidgets.QPushButton(self.frameViolationControl)
        self.btnViolationDeleteAll.setText("")
        self.btnViolationDeleteAll.setIcon(icon6)
        self.btnViolationDeleteAll.setObjectName("btnViolationDeleteAll")
        self.gridLayout_52.addWidget(self.btnViolationDeleteAll, 0, 5, 1, 1)
        self.btnViolationDelete = QtWidgets.QPushButton(self.frameViolationControl)
        self.btnViolationDelete.setText("")
        self.btnViolationDelete.setIcon(icon5)
        self.btnViolationDelete.setObjectName("btnViolationDelete")
        self.gridLayout_52.addWidget(self.btnViolationDelete, 0, 4, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_52.addItem(spacerItem7, 0, 3, 1, 1)
        self.gridLayout_20.addWidget(self.frameViolationControl, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.grpViolations)
        self.frmTotalCharges = QtWidgets.QFrame(self.tabViolations)
        self.frmTotalCharges.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmTotalCharges.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmTotalCharges.setObjectName("frmTotalCharges")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.frmTotalCharges)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.lblTotalCharges = QtWidgets.QLabel(self.frmTotalCharges)
        self.lblTotalCharges.setObjectName("lblTotalCharges")
        self.gridLayout_19.addWidget(self.lblTotalCharges, 0, 0, 1, 1)
        self.fldTotalCharges = QtWidgets.QLineEdit(self.frmTotalCharges)
        self.fldTotalCharges.setObjectName("fldTotalCharges")
        self.gridLayout_19.addWidget(self.fldTotalCharges, 1, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem8, 1, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.frmTotalCharges)
        self.tabWidget.addTab(self.tabViolations, "")
        self.tabAssignments = QtWidgets.QWidget()
        self.tabAssignments.setObjectName("tabAssignments")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.tabAssignments)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.grpAssignments = QtWidgets.QGroupBox(self.tabAssignments)
        self.grpAssignments.setCheckable(True)
        self.grpAssignments.setChecked(False)
        self.grpAssignments.setObjectName("grpAssignments")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.grpAssignments)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.tblAssignments = QtWidgets.QTableWidget(self.grpAssignments)
        self.tblAssignments.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tblAssignments.setAlternatingRowColors(True)
        self.tblAssignments.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblAssignments.setRowCount(20)
        self.tblAssignments.setObjectName("tblAssignments")
        self.tblAssignments.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tblAssignments.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAssignments.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAssignments.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAssignments.setHorizontalHeaderItem(3, item)
        self.tblAssignments.horizontalHeader().setDefaultSectionSize(150)
        self.tblAssignments.horizontalHeader().setStretchLastSection(True)
        self.tblAssignments.verticalHeader().setVisible(False)
        self.gridLayout_22.addWidget(self.tblAssignments, 1, 0, 1, 1)
        self.frameAssignmentControl = QtWidgets.QFrame(self.grpAssignments)
        self.frameAssignmentControl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameAssignmentControl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameAssignmentControl.setObjectName("frameAssignmentControl")
        self.gridLayout_53 = QtWidgets.QGridLayout(self.frameAssignmentControl)
        self.gridLayout_53.setObjectName("gridLayout_53")
        self.btnAssignmentDelete = QtWidgets.QPushButton(self.frameAssignmentControl)
        self.btnAssignmentDelete.setText("")
        self.btnAssignmentDelete.setIcon(icon5)
        self.btnAssignmentDelete.setObjectName("btnAssignmentDelete")
        self.gridLayout_53.addWidget(self.btnAssignmentDelete, 0, 4, 1, 1)
        self.btnAssignmentEdit = QtWidgets.QPushButton(self.frameAssignmentControl)
        self.btnAssignmentEdit.setText("")
        self.btnAssignmentEdit.setIcon(icon7)
        self.btnAssignmentEdit.setObjectName("btnAssignmentEdit")
        self.gridLayout_53.addWidget(self.btnAssignmentEdit, 0, 2, 1, 1)
        self.btnAssignmentView = QtWidgets.QPushButton(self.frameAssignmentControl)
        self.btnAssignmentView.setText("")
        self.btnAssignmentView.setIcon(icon3)
        self.btnAssignmentView.setObjectName("btnAssignmentView")
        self.gridLayout_53.addWidget(self.btnAssignmentView, 0, 1, 1, 1)
        self.btnAssignmentAdd = QtWidgets.QPushButton(self.frameAssignmentControl)
        self.btnAssignmentAdd.setText("")
        self.btnAssignmentAdd.setIcon(icon4)
        self.btnAssignmentAdd.setObjectName("btnAssignmentAdd")
        self.gridLayout_53.addWidget(self.btnAssignmentAdd, 0, 0, 1, 1)
        self.btnAssignmentDeleteAll = QtWidgets.QPushButton(self.frameAssignmentControl)
        self.btnAssignmentDeleteAll.setText("")
        self.btnAssignmentDeleteAll.setIcon(icon6)
        self.btnAssignmentDeleteAll.setObjectName("btnAssignmentDeleteAll")
        self.gridLayout_53.addWidget(self.btnAssignmentDeleteAll, 0, 5, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_53.addItem(spacerItem9, 0, 3, 1, 1)
        self.gridLayout_22.addWidget(self.frameAssignmentControl, 0, 0, 1, 1)
        self.gridLayout_21.addWidget(self.grpAssignments, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabAssignments, "")
        self.tabPropositions = QtWidgets.QWidget()
        self.tabPropositions.setObjectName("tabPropositions")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.tabPropositions)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.grpPropositions = QtWidgets.QGroupBox(self.tabPropositions)
        self.grpPropositions.setCheckable(True)
        self.grpPropositions.setChecked(False)
        self.grpPropositions.setObjectName("grpPropositions")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.grpPropositions)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.tblPropositions = QtWidgets.QTableWidget(self.grpPropositions)
        self.tblPropositions.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tblPropositions.setAlternatingRowColors(True)
        self.tblPropositions.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblPropositions.setRowCount(20)
        self.tblPropositions.setObjectName("tblPropositions")
        self.tblPropositions.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tblPropositions.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblPropositions.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblPropositions.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblPropositions.setHorizontalHeaderItem(3, item)
        self.tblPropositions.horizontalHeader().setDefaultSectionSize(150)
        self.tblPropositions.horizontalHeader().setStretchLastSection(True)
        self.tblPropositions.verticalHeader().setVisible(False)
        self.gridLayout_24.addWidget(self.tblPropositions, 1, 0, 1, 1)
        self.framePropositions = QtWidgets.QFrame(self.grpPropositions)
        self.framePropositions.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePropositions.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePropositions.setObjectName("framePropositions")
        self.gridLayout_54 = QtWidgets.QGridLayout(self.framePropositions)
        self.gridLayout_54.setObjectName("gridLayout_54")
        self.btnPropositionDeleteAll = QtWidgets.QPushButton(self.framePropositions)
        self.btnPropositionDeleteAll.setText("")
        self.btnPropositionDeleteAll.setIcon(icon6)
        self.btnPropositionDeleteAll.setObjectName("btnPropositionDeleteAll")
        self.gridLayout_54.addWidget(self.btnPropositionDeleteAll, 0, 5, 1, 1)
        self.btnPropositionDelete = QtWidgets.QPushButton(self.framePropositions)
        self.btnPropositionDelete.setText("")
        self.btnPropositionDelete.setIcon(icon5)
        self.btnPropositionDelete.setObjectName("btnPropositionDelete")
        self.gridLayout_54.addWidget(self.btnPropositionDelete, 0, 4, 1, 1)
        self.btnPropositionEdit = QtWidgets.QPushButton(self.framePropositions)
        self.btnPropositionEdit.setText("")
        self.btnPropositionEdit.setIcon(icon7)
        self.btnPropositionEdit.setObjectName("btnPropositionEdit")
        self.gridLayout_54.addWidget(self.btnPropositionEdit, 0, 2, 1, 1)
        self.btnPropositionView = QtWidgets.QPushButton(self.framePropositions)
        self.btnPropositionView.setText("")
        self.btnPropositionView.setIcon(icon3)
        self.btnPropositionView.setObjectName("btnPropositionView")
        self.gridLayout_54.addWidget(self.btnPropositionView, 0, 1, 1, 1)
        self.btnPropositionAdd = QtWidgets.QPushButton(self.framePropositions)
        self.btnPropositionAdd.setText("")
        self.btnPropositionAdd.setIcon(icon4)
        self.btnPropositionAdd.setObjectName("btnPropositionAdd")
        self.gridLayout_54.addWidget(self.btnPropositionAdd, 0, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_54.addItem(spacerItem10, 0, 3, 1, 1)
        self.gridLayout_24.addWidget(self.framePropositions, 0, 0, 1, 1)
        self.gridLayout_23.addWidget(self.grpPropositions, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabPropositions, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.frameMainButtons = QtWidgets.QFrame(InspectionDialog)
        self.frameMainButtons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMainButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMainButtons.setObjectName("frameMainButtons")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frameMainButtons)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.btnCancel = QtWidgets.QPushButton(self.frameMainButtons)
        self.btnCancel.setObjectName("btnCancel")
        self.gridLayout_6.addWidget(self.btnCancel, 0, 2, 1, 1)
        self.btnSave = QtWidgets.QPushButton(self.frameMainButtons)
        self.btnSave.setObjectName("btnSave")
        self.gridLayout_6.addWidget(self.btnSave, 0, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem11, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frameMainButtons, 1, 0, 1, 1)

        self.retranslateUi(InspectionDialog)
        self.tabWidget.setCurrentIndex(0)
        self.comboBoxObjectName.setCurrentIndex(-1)
        self.btnCancel.clicked.connect(InspectionDialog.close)
        QtCore.QMetaObject.connectSlotsByName(InspectionDialog)

    def retranslateUi(self, InspectionDialog):
        _translate = QtCore.QCoreApplication.translate
        InspectionDialog.setWindowTitle(_translate("InspectionDialog", "Етапи проведення перевірки"))
        self.grpObject.setTitle(_translate("InspectionDialog", "2. Відомості про об\'єкт перевірки"))
        self.lblObjectName.setText(_translate("InspectionDialog", "Назва об\'єкта"))
        self.btnObject.setToolTip(_translate("InspectionDialog", "Редагування інформації про установи/підрозділи"))
        self.lblObjectCode.setText(_translate("InspectionDialog", "ЄДРПОУ"))
        self.lblObjectAddress.setText(_translate("InspectionDialog", "Адреса об\'єкта"))
        self.grpType.setTitle(_translate("InspectionDialog", "1. Вид перевірки"))
        self.lblType1.setText(_translate("InspectionDialog", "За обсягом"))
        self.cmbType1.setCurrentText(_translate("InspectionDialog", "тематична"))
        self.cmbType1.setItemText(0, _translate("InspectionDialog", "тематична"))
        self.cmbType1.setItemText(1, _translate("InspectionDialog", "комплексна"))
        self.lblType2.setText(_translate("InspectionDialog", "За способом"))
        self.cmbType2.setItemText(0, _translate("InspectionDialog", "позапланова"))
        self.cmbType2.setItemText(1, _translate("InspectionDialog", "планова"))
        self.cmbType2.setItemText(2, _translate("InspectionDialog", "участь"))
        self.lblType3.setText(_translate("InspectionDialog", "За місцем"))
        self.cmbType3.setItemText(0, _translate("InspectionDialog", "невиїзна"))
        self.cmbType3.setItemText(1, _translate("InspectionDialog", "виїзна"))
        self.grpBasis.setTitle(_translate("InspectionDialog", "3. Підстава для проведення перевірки (доручення на проведення перевірки)"))
        self.tblBasis.setSortingEnabled(True)
        item = self.tblBasis.horizontalHeaderItem(0)
        item.setText(_translate("InspectionDialog", "Ініціатор документа"))
        item = self.tblBasis.horizontalHeaderItem(1)
        item.setText(_translate("InspectionDialog", "Вид документа"))
        item = self.tblBasis.horizontalHeaderItem(2)
        item.setText(_translate("InspectionDialog", "Номер"))
        item = self.tblBasis.horizontalHeaderItem(3)
        item.setText(_translate("InspectionDialog", "Дата"))
        item = self.tblBasis.horizontalHeaderItem(4)
        item.setText(_translate("InspectionDialog", "Файл"))
        self.grpPurpose.setTitle(_translate("InspectionDialog", "4. Мета перевірки"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabInitiate), _translate("InspectionDialog", "Ініціювання"))
        self.grpDates.setTitle(_translate("InspectionDialog", "5. Контрольні терміни проведення перевірки"))
        self.lblInspectionFrom.setText(_translate("InspectionDialog", "Дата початку перевірки"))
        self.lblInspectionTo.setText(_translate("InspectionDialog", "Дата закінчення перевірки"))
        self.lblControlDate.setText(_translate("InspectionDialog", "Дата доповіді керівництву"))
        self.lblPeriodFrom.setText(_translate("InspectionDialog", "Дата початку періоду, що охоплюється перевіркою"))
        self.lblPeriodTo.setText(_translate("InspectionDialog", "Дата закінчення періоду, що охоплюється перевіркою"))
        self.lblNewControlDate.setText(_translate("InspectionDialog", "Дата доповіді керівництву перенесена на"))
        self.grpOptions.setTitle(_translate("InspectionDialog", "Опції календаря"))
        self.chkDates.setText(_translate("InspectionDialog", "Термін проведення перевірки"))
        self.chkPeriod.setText(_translate("InspectionDialog", "Період, що охоплюється перевіркою"))
        self.chkControlDate.setText(_translate("InspectionDialog", "Контрольні дати доповіді керівництву"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDates), _translate("InspectionDialog", "Терміни"))
        self.grpGroup.setTitle(_translate("InspectionDialog", "6. Склад робочої групи (кількість та склад посадових осіб, які проводять перевірку)"))
        self.tblGroup.setSortingEnabled(True)
        item = self.tblGroup.horizontalHeaderItem(0)
        item.setText(_translate("InspectionDialog", "Функція"))
        item = self.tblGroup.horizontalHeaderItem(1)
        item.setText(_translate("InspectionDialog", "ПІБ"))
        item = self.tblGroup.horizontalHeaderItem(2)
        item.setText(_translate("InspectionDialog", "Посада"))
        item = self.tblGroup.horizontalHeaderItem(3)
        item.setText(_translate("InspectionDialog", "Установа"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGroup), _translate("InspectionDialog", "Робоча група"))
        self.grpStopContinue.setTitle(_translate("InspectionDialog", "7. Необхідність зупинення/продовження перевірки"))
        self.tblStopContinue.setSortingEnabled(True)
        item = self.tblStopContinue.horizontalHeaderItem(0)
        item.setText(_translate("InspectionDialog", "Дія"))
        item = self.tblStopContinue.horizontalHeaderItem(1)
        item.setText(_translate("InspectionDialog", "Дата з"))
        item = self.tblStopContinue.horizontalHeaderItem(2)
        item.setText(_translate("InspectionDialog", "Дата до"))
        item = self.tblStopContinue.horizontalHeaderItem(3)
        item.setText(_translate("InspectionDialog", "Підстава"))
        self.grpRefuse.setTitle(_translate("InspectionDialog", "8. Ненадання, несвоєчасне надання, надання не в повному обсязі пояснень і підтверджуючих документів"))
        self.tblRefuse.setSortingEnabled(True)
        item = self.tblRefuse.horizontalHeaderItem(0)
        item.setText(_translate("InspectionDialog", "Номер акта"))
        item = self.tblRefuse.horizontalHeaderItem(1)
        item.setText(_translate("InspectionDialog", "Дата акта"))
        item = self.tblRefuse.horizontalHeaderItem(2)
        item.setText(_translate("InspectionDialog", "Файл"))
        item = self.tblRefuse.horizontalHeaderItem(3)
        item.setText(_translate("InspectionDialog", "Зміст події"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabConduct), _translate("InspectionDialog", "Хід перевірки"))
        self.grpResultDocs.setTitle(_translate("InspectionDialog", "9. Документи щодо результатів перевірки"))
        self.tblResultDocs.setSortingEnabled(True)
        item = self.tblResultDocs.horizontalHeaderItem(0)
        item.setText(_translate("InspectionDialog", "Вид документа"))
        item = self.tblResultDocs.horizontalHeaderItem(1)
        item.setText(_translate("InspectionDialog", "Номер"))
        item = self.tblResultDocs.horizontalHeaderItem(2)
        item.setText(_translate("InspectionDialog", "Дата"))
        item = self.tblResultDocs.horizontalHeaderItem(3)
        item.setText(_translate("InspectionDialog", "Файл"))
        self.grpEnforcement.setTitle(_translate("InspectionDialog", "10. Матеріали перевірки передано до..."))
        self.chkEnforcement.setText(_translate("InspectionDialog", "правоохоронних органів"))
        self.chkInternalSecurity.setText(_translate("InspectionDialog", "підрозділів внутрішньої безпеки"))
        self.chkFinish.setText(_translate("InspectionDialog", "ЗАВРШЕННЯ ВНУТРІШНЬОЇ ПЕРЕВІРКИ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFinish), _translate("InspectionDialog", "Завершення"))
        self.grpViolations.setTitle(_translate("InspectionDialog", "Наявність виявлених порушень за результатами перевірки"))
        self.tblViolations.setSortingEnabled(True)
        item = self.tblViolations.horizontalHeaderItem(0)
        item.setText(_translate("InspectionDialog", "Вид порушення"))
        item = self.tblViolations.horizontalHeaderItem(1)
        item.setText(_translate("InspectionDialog", "Сума порушення"))
        item = self.tblViolations.horizontalHeaderItem(2)
        item.setText(_translate("InspectionDialog", "Зміст порушення"))
        self.lblTotalCharges.setText(_translate("InspectionDialog", "Загальна сума несплачених митних платежів"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabViolations), _translate("InspectionDialog", "Порушення"))
        self.grpAssignments.setTitle(_translate("InspectionDialog", "Наявність доручень щодо усунення виявлених за результатами перевірки порушень"))
        self.tblAssignments.setSortingEnabled(True)
        item = self.tblAssignments.horizontalHeaderItem(0)
        item.setText(_translate("InspectionDialog", "Пункт №"))
        item = self.tblAssignments.horizontalHeaderItem(1)
        item.setText(_translate("InspectionDialog", "Відповідальна особа"))
        item = self.tblAssignments.horizontalHeaderItem(2)
        item.setText(_translate("InspectionDialog", "Зміст"))
        item = self.tblAssignments.horizontalHeaderItem(3)
        item.setText(_translate("InspectionDialog", "Термін"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAssignments), _translate("InspectionDialog", "Доручення"))
        self.grpPropositions.setTitle(_translate("InspectionDialog", "Наявність пропозицій про застосування заходів дисциплінарного впливу за результатами перевірки"))
        self.tblPropositions.setSortingEnabled(True)
        item = self.tblPropositions.horizontalHeaderItem(0)
        item.setText(_translate("InspectionDialog", "Номенклатура"))
        item = self.tblPropositions.horizontalHeaderItem(1)
        item.setText(_translate("InspectionDialog", "ПІБ"))
        item = self.tblPropositions.horizontalHeaderItem(2)
        item.setText(_translate("InspectionDialog", "Посада"))
        item = self.tblPropositions.horizontalHeaderItem(3)
        item.setText(_translate("InspectionDialog", "Установа"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPropositions), _translate("InspectionDialog", "Пропозиції"))
        self.btnCancel.setText(_translate("InspectionDialog", "Відмінити"))
        self.btnSave.setText(_translate("InspectionDialog", "Зберегти"))

import icons

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    InspectionDialog = QtWidgets.QDialog()
    ui = Ui_InspectionDialog()
    ui.setupUi(InspectionDialog)
    InspectionDialog.show()
    sys.exit(app.exec_())
