# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainform.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(912, 817)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/Icons/navigation/034.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.MainForm = QtWidgets.QWidget(MainWindow)
        self.MainForm.setEnabled(True)
        self.MainForm.setObjectName("MainForm")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.MainForm)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.MainForm)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tabWidget.setFont(font)
        self.tabWidget.setIconSize(QtCore.QSize(24, 24))
        self.tabWidget.setObjectName("tabWidget")
        self.tabCalendar = QtWidgets.QWidget()
        self.tabCalendar.setObjectName("tabCalendar")
        self.gridLayout = QtWidgets.QGridLayout(self.tabCalendar)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.tabCalendar)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.widget)
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout_2.addWidget(self.calendarWidget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 1, 0, 1, 1)
        self.groupBoxOptions = QtWidgets.QGroupBox(self.tabCalendar)
        self.groupBoxOptions.setObjectName("groupBoxOptions")
        self.formLayout = QtWidgets.QFormLayout(self.groupBoxOptions)
        self.formLayout.setObjectName("formLayout")
        self.checkBoxAll = QtWidgets.QCheckBox(self.groupBoxOptions)
        self.checkBoxAll.setObjectName("checkBoxAll")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.checkBoxAll)
        self.checkBoxPlan = QtWidgets.QCheckBox(self.groupBoxOptions)
        self.checkBoxPlan.setObjectName("checkBoxPlan")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.checkBoxPlan)
        self.checkBoxOutplan = QtWidgets.QCheckBox(self.groupBoxOptions)
        self.checkBoxOutplan.setObjectName("checkBoxOutplan")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.checkBoxOutplan)
        self.checkBoxTakePart = QtWidgets.QCheckBox(self.groupBoxOptions)
        self.checkBoxTakePart.setObjectName("checkBoxTakePart")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.checkBoxTakePart)
        self.checkBoxOfficials = QtWidgets.QCheckBox(self.groupBoxOptions)
        self.checkBoxOfficials.setObjectName("checkBoxOfficials")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.checkBoxOfficials)
        self.checkBoxObjects = QtWidgets.QCheckBox(self.groupBoxOptions)
        self.checkBoxObjects.setObjectName("checkBoxObjects")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.checkBoxObjects)
        self.gridLayout.addWidget(self.groupBoxOptions, 1, 1, 1, 1)
        self.labelHeadCalendar = QtWidgets.QLabel(self.tabCalendar)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelHeadCalendar.setFont(font)
        self.labelHeadCalendar.setObjectName("labelHeadCalendar")
        self.gridLayout.addWidget(self.labelHeadCalendar, 0, 0, 1, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ico/Icons/work/015.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabCalendar, icon1, "")
        self.tabPlans = QtWidgets.QWidget()
        self.tabPlans.setObjectName("tabPlans")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tabPlans)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableWidgetPlans = QtWidgets.QTableWidget(self.tabPlans)
        self.tableWidgetPlans.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableWidgetPlans.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetPlans.setTabKeyNavigation(False)
        self.tableWidgetPlans.setProperty("showDropIndicator", False)
        self.tableWidgetPlans.setDragDropOverwriteMode(False)
        self.tableWidgetPlans.setAlternatingRowColors(True)
        self.tableWidgetPlans.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidgetPlans.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidgetPlans.setWordWrap(False)
        self.tableWidgetPlans.setCornerButtonEnabled(False)
        self.tableWidgetPlans.setRowCount(25)
        self.tableWidgetPlans.setObjectName("tableWidgetPlans")
        self.tableWidgetPlans.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetPlans.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetPlans.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetPlans.setHorizontalHeaderItem(2, item)
        self.tableWidgetPlans.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidgetPlans.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetPlans.verticalHeader().setVisible(False)
        self.gridLayout_4.addWidget(self.tableWidgetPlans, 2, 0, 1, 1)
        self.framePlanControl = QtWidgets.QFrame(self.tabPlans)
        self.framePlanControl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePlanControl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePlanControl.setObjectName("framePlanControl")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.framePlanControl)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.btnPlanDelete = QtWidgets.QPushButton(self.framePlanControl)
        self.btnPlanDelete.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ico/Icons/basic/059.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPlanDelete.setIcon(icon2)
        self.btnPlanDelete.setObjectName("btnPlanDelete")
        self.gridLayout_12.addWidget(self.btnPlanDelete, 0, 4, 1, 1)
        self.btnPlanEdit = QtWidgets.QPushButton(self.framePlanControl)
        self.btnPlanEdit.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/ico/Icons/education/027.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPlanEdit.setIcon(icon3)
        self.btnPlanEdit.setObjectName("btnPlanEdit")
        self.gridLayout_12.addWidget(self.btnPlanEdit, 0, 2, 1, 1)
        self.btnPlanAdd = QtWidgets.QPushButton(self.framePlanControl)
        self.btnPlanAdd.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/ico/Icons/basic/058.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPlanAdd.setIcon(icon4)
        self.btnPlanAdd.setObjectName("btnPlanAdd")
        self.gridLayout_12.addWidget(self.btnPlanAdd, 0, 0, 1, 1)
        self.btnPlanView = QtWidgets.QPushButton(self.framePlanControl)
        self.btnPlanView.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/ico/Icons/basic/064.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPlanView.setIcon(icon5)
        self.btnPlanView.setObjectName("btnPlanView")
        self.gridLayout_12.addWidget(self.btnPlanView, 0, 1, 1, 1)
        self.btnPlanDeleteAll = QtWidgets.QPushButton(self.framePlanControl)
        self.btnPlanDeleteAll.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/ico/Icons/basic/060.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPlanDeleteAll.setIcon(icon6)
        self.btnPlanDeleteAll.setObjectName("btnPlanDeleteAll")
        self.gridLayout_12.addWidget(self.btnPlanDeleteAll, 0, 5, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem, 0, 3, 1, 1)
        self.gridLayout_4.addWidget(self.framePlanControl, 1, 0, 1, 1)
        self.labelHeadPlans = QtWidgets.QLabel(self.tabPlans)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelHeadPlans.setFont(font)
        self.labelHeadPlans.setObjectName("labelHeadPlans")
        self.gridLayout_4.addWidget(self.labelHeadPlans, 0, 0, 1, 1)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/ico/Icons/work/018.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabPlans, icon7, "")
        self.tabInspections = QtWidgets.QWidget()
        self.tabInspections.setObjectName("tabInspections")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tabInspections)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frameInspectionControl = QtWidgets.QFrame(self.tabInspections)
        self.frameInspectionControl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameInspectionControl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameInspectionControl.setObjectName("frameInspectionControl")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frameInspectionControl)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.btnInspectionDeleteAll = QtWidgets.QPushButton(self.frameInspectionControl)
        self.btnInspectionDeleteAll.setText("")
        self.btnInspectionDeleteAll.setIcon(icon6)
        self.btnInspectionDeleteAll.setObjectName("btnInspectionDeleteAll")
        self.gridLayout_13.addWidget(self.btnInspectionDeleteAll, 0, 5, 1, 1)
        self.btnInspectionDelete = QtWidgets.QPushButton(self.frameInspectionControl)
        self.btnInspectionDelete.setText("")
        self.btnInspectionDelete.setIcon(icon2)
        self.btnInspectionDelete.setObjectName("btnInspectionDelete")
        self.gridLayout_13.addWidget(self.btnInspectionDelete, 0, 4, 1, 1)
        self.btnInspectionView = QtWidgets.QPushButton(self.frameInspectionControl)
        self.btnInspectionView.setText("")
        self.btnInspectionView.setIcon(icon5)
        self.btnInspectionView.setObjectName("btnInspectionView")
        self.gridLayout_13.addWidget(self.btnInspectionView, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem1, 0, 3, 1, 1)
        self.btnInspectionAdd = QtWidgets.QPushButton(self.frameInspectionControl)
        self.btnInspectionAdd.setText("")
        self.btnInspectionAdd.setIcon(icon4)
        self.btnInspectionAdd.setObjectName("btnInspectionAdd")
        self.gridLayout_13.addWidget(self.btnInspectionAdd, 0, 0, 1, 1)
        self.btnInspectionEdit = QtWidgets.QPushButton(self.frameInspectionControl)
        self.btnInspectionEdit.setText("")
        self.btnInspectionEdit.setIcon(icon3)
        self.btnInspectionEdit.setObjectName("btnInspectionEdit")
        self.gridLayout_13.addWidget(self.btnInspectionEdit, 0, 2, 1, 1)
        self.gridLayout_5.addWidget(self.frameInspectionControl, 1, 0, 1, 1)
        self.labelHeadInspections = QtWidgets.QLabel(self.tabInspections)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.labelHeadInspections.setFont(font)
        self.labelHeadInspections.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelHeadInspections.setObjectName("labelHeadInspections")
        self.gridLayout_5.addWidget(self.labelHeadInspections, 0, 0, 1, 1)
        self.tableWidgetInspections = QtWidgets.QTableWidget(self.tabInspections)
        self.tableWidgetInspections.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidgetInspections.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetInspections.setTabKeyNavigation(False)
        self.tableWidgetInspections.setProperty("showDropIndicator", False)
        self.tableWidgetInspections.setDragDropOverwriteMode(False)
        self.tableWidgetInspections.setAlternatingRowColors(True)
        self.tableWidgetInspections.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidgetInspections.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidgetInspections.setObjectName("tableWidgetInspections")
        self.tableWidgetInspections.setColumnCount(9)
        self.tableWidgetInspections.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetInspections.setHorizontalHeaderItem(0, item)
        self.tableWidgetInspections.setColumnWidth(0, 10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetInspections.setHorizontalHeaderItem(1, item)
        self.tableWidgetInspections.setColumnWidth(1, 75)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetInspections.setHorizontalHeaderItem(2, item)
        self.tableWidgetInspections.setColumnWidth(2, 80)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetInspections.setHorizontalHeaderItem(3, item)
        self.tableWidgetInspections.setColumnWidth(3, 75)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetInspections.setHorizontalHeaderItem(4, item)
        self.tableWidgetInspections.horizontalHeader().setSectionResizeMode(4, QtWidgets.QHeaderView.Stretch)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetInspections.setHorizontalHeaderItem(5, item)
        self.tableWidgetInspections.setColumnWidth(5, 75)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetInspections.setHorizontalHeaderItem(6, item)
        self.tableWidgetInspections.setColumnWidth(6, 80)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetInspections.setHorizontalHeaderItem(7, item)
        self.tableWidgetInspections.setColumnWidth(7, 85)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetInspections.setHorizontalHeaderItem(8, item)
        self.tableWidgetInspections.setColumnWidth(8, 80)
        self.tableWidgetInspections.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidgetInspections.verticalHeader().setVisible(False)
        self.gridLayout_5.addWidget(self.tableWidgetInspections, 2, 0, 1, 1)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/ico/Icons/work/006.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabInspections, icon8, "")
        self.tabMonitoring = QtWidgets.QWidget()
        self.tabMonitoring.setObjectName("tabMonitoring")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tabMonitoring)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.toolBoxMonitoring = QtWidgets.QToolBox(self.tabMonitoring)
        self.toolBoxMonitoring.setObjectName("toolBoxMonitoring")
        self.pageExecution = QtWidgets.QWidget()
        self.pageExecution.setGeometry(QtCore.QRect(0, 0, 870, 539))
        self.pageExecution.setObjectName("pageExecution")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.pageExecution)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tableWidgetExecution = QtWidgets.QTableWidget(self.pageExecution)
        self.tableWidgetExecution.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableWidgetExecution.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetExecution.setTabKeyNavigation(False)
        self.tableWidgetExecution.setProperty("showDropIndicator", False)
        self.tableWidgetExecution.setDragDropOverwriteMode(False)
        self.tableWidgetExecution.setAlternatingRowColors(True)
        self.tableWidgetExecution.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidgetExecution.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidgetExecution.setWordWrap(False)
        self.tableWidgetExecution.setCornerButtonEnabled(False)
        self.tableWidgetExecution.setRowCount(25)
        self.tableWidgetExecution.setObjectName("tableWidgetExecution")
        self.tableWidgetExecution.setColumnCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetExecution.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetExecution.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetExecution.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetExecution.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetExecution.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetExecution.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetExecution.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetExecution.setHorizontalHeaderItem(7, item)
        self.tableWidgetExecution.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidgetExecution.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetExecution.verticalHeader().setVisible(False)
        self.gridLayout_8.addWidget(self.tableWidgetExecution, 0, 0, 1, 1)
        self.toolBoxMonitoring.addItem(self.pageExecution, "")
        self.pageElimination = QtWidgets.QWidget()
        self.pageElimination.setGeometry(QtCore.QRect(0, 0, 98, 89))
        self.pageElimination.setObjectName("pageElimination")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.pageElimination)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.tableWidgetElimination = QtWidgets.QTableWidget(self.pageElimination)
        self.tableWidgetElimination.setObjectName("tableWidgetElimination")
        self.tableWidgetElimination.setColumnCount(0)
        self.tableWidgetElimination.setRowCount(0)
        self.gridLayout_9.addWidget(self.tableWidgetElimination, 0, 0, 1, 1)
        self.toolBoxMonitoring.addItem(self.pageElimination, "")
        self.gridLayout_6.addWidget(self.toolBoxMonitoring, 1, 0, 1, 1)
        self.frameMonitoringControl = QtWidgets.QFrame(self.tabMonitoring)
        self.frameMonitoringControl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMonitoringControl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMonitoringControl.setObjectName("frameMonitoringControl")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frameMonitoringControl)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.btnTaskNotdone = QtWidgets.QPushButton(self.frameMonitoringControl)
        self.btnTaskNotdone.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/ico/Icons/basic/020.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnTaskNotdone.setIcon(icon9)
        self.btnTaskNotdone.setCheckable(True)
        self.btnTaskNotdone.setObjectName("btnTaskNotdone")
        self.gridLayout_14.addWidget(self.btnTaskNotdone, 0, 7, 1, 1)
        self.btnMonitoringView = QtWidgets.QPushButton(self.frameMonitoringControl)
        self.btnMonitoringView.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/ico/Icons/education/020.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMonitoringView.setIcon(icon10)
        self.btnMonitoringView.setObjectName("btnMonitoringView")
        self.gridLayout_14.addWidget(self.btnMonitoringView, 0, 0, 1, 1)
        self.btnTaskDone = QtWidgets.QPushButton(self.frameMonitoringControl)
        self.btnTaskDone.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/ico/Icons/basic/023.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnTaskDone.setIcon(icon11)
        self.btnTaskDone.setObjectName("btnTaskDone")
        self.gridLayout_14.addWidget(self.btnTaskDone, 0, 6, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem2, 0, 3, 1, 1)
        self.btnMonitoringEdit = QtWidgets.QPushButton(self.frameMonitoringControl)
        self.btnMonitoringEdit.setText("")
        self.btnMonitoringEdit.setIcon(icon3)
        self.btnMonitoringEdit.setObjectName("btnMonitoringEdit")
        self.gridLayout_14.addWidget(self.btnMonitoringEdit, 0, 1, 1, 1)
        self.btnTaskDeadline = QtWidgets.QPushButton(self.frameMonitoringControl)
        self.btnTaskDeadline.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/ico/Icons/education/004.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnTaskDeadline.setIcon(icon12)
        self.btnTaskDeadline.setObjectName("btnTaskDeadline")
        self.gridLayout_14.addWidget(self.btnTaskDeadline, 0, 5, 1, 1)
        self.btnTaskCloseDate = QtWidgets.QPushButton(self.frameMonitoringControl)
        self.btnTaskCloseDate.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/ico/Icons/basic/018.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnTaskCloseDate.setIcon(icon13)
        self.btnTaskCloseDate.setObjectName("btnTaskCloseDate")
        self.gridLayout_14.addWidget(self.btnTaskCloseDate, 0, 4, 1, 1)
        self.btnMonitoringCorrespondence = QtWidgets.QPushButton(self.frameMonitoringControl)
        self.btnMonitoringCorrespondence.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/ico/Icons/work/037.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMonitoringCorrespondence.setIcon(icon14)
        self.btnMonitoringCorrespondence.setObjectName("btnMonitoringCorrespondence")
        self.gridLayout_14.addWidget(self.btnMonitoringCorrespondence, 0, 2, 1, 1)
        self.gridLayout_6.addWidget(self.frameMonitoringControl, 0, 0, 1, 1)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/ico/Icons/devices/055.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabMonitoring, icon15, "")
        self.tabReports = QtWidgets.QWidget()
        self.tabReports.setObjectName("tabReports")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tabReports)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.toolBoxReports = QtWidgets.QToolBox(self.tabReports)
        self.toolBoxReports.setObjectName("toolBoxReports")
        self.pageReports = QtWidgets.QWidget()
        self.pageReports.setGeometry(QtCore.QRect(0, 0, 98, 91))
        self.pageReports.setObjectName("pageReports")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.pageReports)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.listWidgetReports = QtWidgets.QListWidget(self.pageReports)
        self.listWidgetReports.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.listWidgetReports.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listWidgetReports.setProperty("showDropIndicator", False)
        self.listWidgetReports.setDefaultDropAction(QtCore.Qt.LinkAction)
        self.listWidgetReports.setAlternatingRowColors(True)
        self.listWidgetReports.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listWidgetReports.setMovement(QtWidgets.QListView.Static)
        self.listWidgetReports.setGridSize(QtCore.QSize(1, 0))
        self.listWidgetReports.setModelColumn(0)
        self.listWidgetReports.setSelectionRectVisible(True)
        self.listWidgetReports.setObjectName("listWidgetReports")
        item = QtWidgets.QListWidgetItem()
        self.listWidgetReports.addItem(item)
        self.gridLayout_10.addWidget(self.listWidgetReports, 0, 0, 1, 1)
        self.toolBoxReports.addItem(self.pageReports, "")
        self.pageDiagrams = QtWidgets.QWidget()
        self.pageDiagrams.setGeometry(QtCore.QRect(0, 0, 870, 589))
        self.pageDiagrams.setObjectName("pageDiagrams")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.pageDiagrams)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.listWidgetDiagrams = QtWidgets.QListWidget(self.pageDiagrams)
        self.listWidgetDiagrams.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listWidgetDiagrams.setProperty("showDropIndicator", False)
        self.listWidgetDiagrams.setDefaultDropAction(QtCore.Qt.LinkAction)
        self.listWidgetDiagrams.setAlternatingRowColors(True)
        self.listWidgetDiagrams.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listWidgetDiagrams.setGridSize(QtCore.QSize(1, 0))
        self.listWidgetDiagrams.setSelectionRectVisible(True)
        self.listWidgetDiagrams.setObjectName("listWidgetDiagrams")
        item = QtWidgets.QListWidgetItem()
        self.listWidgetDiagrams.addItem(item)
        self.gridLayout_11.addWidget(self.listWidgetDiagrams, 0, 0, 1, 1)
        self.toolBoxReports.addItem(self.pageDiagrams, "")
        self.gridLayout_7.addWidget(self.toolBoxReports, 0, 0, 1, 1)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/ico/Icons/education/011.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabReports, icon16, "")
        self.gridLayout_3.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.frameHead = QtWidgets.QFrame(self.MainForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameHead.sizePolicy().hasHeightForWidth())
        self.frameHead.setSizePolicy(sizePolicy)
        self.frameHead.setMaximumSize(QtCore.QSize(16777215, 95))
        self.frameHead.setSizeIncrement(QtCore.QSize(0, 0))
        self.frameHead.setBaseSize(QtCore.QSize(0, 0))
        self.frameHead.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameHead.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameHead.setObjectName("frameHead")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frameHead)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.frameLogin = QtWidgets.QFrame(self.frameHead)
        self.frameLogin.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLogin.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLogin.setObjectName("frameLogin")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frameLogin)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.btnLogin = QtWidgets.QPushButton(self.frameLogin)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.btnLogin.setFont(font)
        self.btnLogin.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/ico/Icons/work/028.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLogin.setIcon(icon17)
        self.btnLogin.setIconSize(QtCore.QSize(24, 24))
        self.btnLogin.setObjectName("btnLogin")
        self.gridLayout_16.addWidget(self.btnLogin, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem3, 1, 0, 1, 1)
        self.gridLayout_15.addWidget(self.frameLogin, 0, 2, 1, 1)
        self.labelLogoImage = QtWidgets.QLabel(self.frameHead)
        self.labelLogoImage.setScaledContents(True)
        self.labelLogoImage.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelLogoImage.setIndent(-1)
        self.labelLogoImage.setObjectName("labelLogoImage")
        self.gridLayout_15.addWidget(self.labelLogoImage, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem4, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frameHead, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.MainForm)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.toolBoxMonitoring.setCurrentIndex(0)
        self.toolBoxReports.setCurrentIndex(1)
        self.listWidgetReports.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "РЕВІЗОР-2019"))
        self.groupBoxOptions.setTitle(_translate("MainWindow", "Перегляд за опціями"))
        self.checkBoxAll.setText(_translate("MainWindow", "всі перевірки"))
        self.checkBoxPlan.setText(_translate("MainWindow", "планові"))
        self.checkBoxOutplan.setText(_translate("MainWindow", "позапланові"))
        self.checkBoxTakePart.setText(_translate("MainWindow", "участь"))
        self.checkBoxOfficials.setText(_translate("MainWindow", "в розрізі посадових осіб"))
        self.checkBoxObjects.setText(_translate("MainWindow", "в розрізі об\'єктів перевірки"))
        self.labelHeadCalendar.setText(_translate("MainWindow", "Календар контрольно-перевірочної роботи"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCalendar), _translate("MainWindow", "Календар"))
        self.tableWidgetPlans.setSortingEnabled(True)
        item = self.tableWidgetPlans.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Рік"))
        item = self.tableWidgetPlans.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Квартал"))
        item = self.tableWidgetPlans.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Назва плану"))
        self.btnPlanDelete.setToolTip(_translate("MainWindow", "Видалити план"))
        self.btnPlanEdit.setToolTip(_translate("MainWindow", "Редагувати план"))
        self.btnPlanAdd.setToolTip(_translate("MainWindow", "Створити новий план"))
        self.btnPlanView.setToolTip(_translate("MainWindow", "Переглянути план"))
        self.btnPlanDeleteAll.setToolTip(_translate("MainWindow", "Видалити всі записи"))
        self.labelHeadPlans.setText(_translate("MainWindow", "Перелік планів діяльності"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPlans), _translate("MainWindow", "Планування"))
        self.btnInspectionDeleteAll.setToolTip(_translate("MainWindow", "Видалити всі записи"))
        self.btnInspectionDelete.setToolTip(_translate("MainWindow", "Видалити перевірку"))
        self.btnInspectionView.setToolTip(_translate("MainWindow", "Переглянути перевірку"))
        self.btnInspectionAdd.setToolTip(_translate("MainWindow", "Створити нову перевірку"))
        self.btnInspectionEdit.setToolTip(_translate("MainWindow", "Редагувати перевірку"))
        self.labelHeadInspections.setText(_translate("MainWindow", "Перелік призначених внутрішніх перевірок"))
        self.tableWidgetInspections.setSortingEnabled(True)
        item = self.tableWidgetInspections.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "№"))
        item = self.tableWidgetInspections.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "За обсягом"))
        item = self.tableWidgetInspections.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "За способом"))
        item = self.tableWidgetInspections.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "За місцем"))
        item = self.tableWidgetInspections.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Об\'єкт"))
        item = self.tableWidgetInspections.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "ЄДРПОУ"))
        item = self.tableWidgetInspections.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Перевірка з"))
        item = self.tableWidgetInspections.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Перевірка до"))
        item = self.tableWidgetInspections.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Доповідь"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabInspections), _translate("MainWindow", "Перевірки"))
        self.tableWidgetExecution.setSortingEnabled(True)
        item = self.tableWidgetExecution.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Пер. №"))
        item = self.tableWidgetExecution.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Доручення"))
        item = self.tableWidgetExecution.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Номер"))
        item = self.tableWidgetExecution.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Дата"))
        item = self.tableWidgetExecution.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Пункт №"))
        item = self.tableWidgetExecution.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Відповідальний"))
        item = self.tableWidgetExecution.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Термін"))
        item = self.tableWidgetExecution.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Зміст"))
        self.toolBoxMonitoring.setItemText(self.toolBoxMonitoring.indexOf(self.pageExecution), _translate("MainWindow", "Моніторинг виконання доручень"))
        self.toolBoxMonitoring.setItemText(self.toolBoxMonitoring.indexOf(self.pageElimination), _translate("MainWindow", "Моніторинг усунення недоліків"))
        self.btnTaskNotdone.setToolTip(_translate("MainWindow", "Невиконані завдання"))
        self.btnMonitoringView.setToolTip(_translate("MainWindow", "Преглянути доручення"))
        self.btnTaskDone.setToolTip(_translate("MainWindow", "Виконані завдання"))
        self.btnMonitoringEdit.setToolTip(_translate("MainWindow", "Редагувати доручення"))
        self.btnTaskDeadline.setToolTip(_translate("MainWindow", "Термін порушено"))
        self.btnTaskCloseDate.setToolTip(_translate("MainWindow", "Термін спливає"))
        self.btnMonitoringCorrespondence.setToolTip(_translate("MainWindow", "Листування"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMonitoring), _translate("MainWindow", "Моніторинг"))
        self.listWidgetReports.setSortingEnabled(False)
        __sortingEnabled = self.listWidgetReports.isSortingEnabled()
        self.listWidgetReports.setSortingEnabled(False)
        item = self.listWidgetReports.item(0)
        item.setText(_translate("MainWindow", "Назва звіту"))
        self.listWidgetReports.setSortingEnabled(__sortingEnabled)
        self.toolBoxReports.setItemText(self.toolBoxReports.indexOf(self.pageReports), _translate("MainWindow", "Перелік звітів"))
        __sortingEnabled = self.listWidgetDiagrams.isSortingEnabled()
        self.listWidgetDiagrams.setSortingEnabled(False)
        item = self.listWidgetDiagrams.item(0)
        item.setText(_translate("MainWindow", "Назва діаграми"))
        self.listWidgetDiagrams.setSortingEnabled(__sortingEnabled)
        self.toolBoxReports.setItemText(self.toolBoxReports.indexOf(self.pageDiagrams), _translate("MainWindow", "Перелік діаграм"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabReports), _translate("MainWindow", "Звіти"))
        self.labelLogoImage.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/img/Images/logo_audit.png\"/></p></body></html>"))

import icons
import images

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
