# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'orgform.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogOrgChoose(object):
    def setupUi(self, DialogOrgChoose):
        DialogOrgChoose.setObjectName("DialogOrgChoose")
        DialogOrgChoose.setWindowModality(QtCore.Qt.ApplicationModal)
        DialogOrgChoose.resize(625, 487)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogOrgChoose.sizePolicy().hasHeightForWidth())
        DialogOrgChoose.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/Icons/finance/014.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogOrgChoose.setWindowIcon(icon)
        DialogOrgChoose.setModal(False)
        self.gridLayout = QtWidgets.QGridLayout(DialogOrgChoose)
        self.gridLayout.setObjectName("gridLayout")
        self.frameButtons = QtWidgets.QFrame(DialogOrgChoose)
        self.frameButtons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameButtons.setObjectName("frameButtons")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frameButtons)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 1)
        self.btnOrgEdit = QtWidgets.QPushButton(self.frameButtons)
        self.btnOrgEdit.setObjectName("btnOrgEdit")
        self.gridLayout_2.addWidget(self.btnOrgEdit, 0, 3, 1, 1)
        self.btnOrgAdd = QtWidgets.QPushButton(self.frameButtons)
        self.btnOrgAdd.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ico/Icons/basic/021.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnOrgAdd.setIcon(icon1)
        self.btnOrgAdd.setObjectName("btnOrgAdd")
        self.gridLayout_2.addWidget(self.btnOrgAdd, 0, 0, 1, 1)
        self.btnOrgCancel = QtWidgets.QPushButton(self.frameButtons)
        self.btnOrgCancel.setObjectName("btnOrgCancel")
        self.gridLayout_2.addWidget(self.btnOrgCancel, 0, 4, 1, 1)
        self.btnOrgDelete = QtWidgets.QPushButton(self.frameButtons)
        self.btnOrgDelete.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ico/Icons/basic/022.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnOrgDelete.setIcon(icon2)
        self.btnOrgDelete.setObjectName("btnOrgDelete")
        self.gridLayout_2.addWidget(self.btnOrgDelete, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.frameButtons, 5, 1, 1, 1)
        self.frameOrganization = QtWidgets.QFrame(DialogOrgChoose)
        self.frameOrganization.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameOrganization.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameOrganization.setObjectName("frameOrganization")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frameOrganization)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelOrgAddress = QtWidgets.QLabel(self.frameOrganization)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelOrgAddress.sizePolicy().hasHeightForWidth())
        self.labelOrgAddress.setSizePolicy(sizePolicy)
        self.labelOrgAddress.setObjectName("labelOrgAddress")
        self.gridLayout_3.addWidget(self.labelOrgAddress, 5, 0, 1, 1)
        self.lineEditOrgName = QtWidgets.QLineEdit(self.frameOrganization)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditOrgName.sizePolicy().hasHeightForWidth())
        self.lineEditOrgName.setSizePolicy(sizePolicy)
        self.lineEditOrgName.setObjectName("lineEditOrgName")
        self.gridLayout_3.addWidget(self.lineEditOrgName, 2, 1, 1, 1)
        self.labelOrgName = QtWidgets.QLabel(self.frameOrganization)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelOrgName.sizePolicy().hasHeightForWidth())
        self.labelOrgName.setSizePolicy(sizePolicy)
        self.labelOrgName.setObjectName("labelOrgName")
        self.gridLayout_3.addWidget(self.labelOrgName, 2, 0, 1, 1)
        self.labelOrgCode = QtWidgets.QLabel(self.frameOrganization)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelOrgCode.sizePolicy().hasHeightForWidth())
        self.labelOrgCode.setSizePolicy(sizePolicy)
        self.labelOrgCode.setObjectName("labelOrgCode")
        self.gridLayout_3.addWidget(self.labelOrgCode, 4, 0, 1, 1)
        self.lineEditOrgCode = QtWidgets.QLineEdit(self.frameOrganization)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditOrgCode.sizePolicy().hasHeightForWidth())
        self.lineEditOrgCode.setSizePolicy(sizePolicy)
        self.lineEditOrgCode.setObjectName("lineEditOrgCode")
        self.gridLayout_3.addWidget(self.lineEditOrgCode, 4, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 1, 1, 1)
        self.lineEditOrgAddress = QtWidgets.QLineEdit(self.frameOrganization)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditOrgAddress.sizePolicy().hasHeightForWidth())
        self.lineEditOrgAddress.setSizePolicy(sizePolicy)
        self.lineEditOrgAddress.setObjectName("lineEditOrgAddress")
        self.gridLayout_3.addWidget(self.lineEditOrgAddress, 5, 1, 1, 1)
        self.gridLayout.addWidget(self.frameOrganization, 1, 1, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(DialogOrgChoose)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget.setColumnWidth(0, 250)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.setColumnWidth(1, 75)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tableWidget, 0, 1, 1, 1)

        self.retranslateUi(DialogOrgChoose)
        QtCore.QMetaObject.connectSlotsByName(DialogOrgChoose)

    def retranslateUi(self, DialogOrgChoose):
        _translate = QtCore.QCoreApplication.translate
        DialogOrgChoose.setWindowTitle(_translate("DialogOrgChoose", "Додати/редагувати установи/підрозділи"))
        self.btnOrgEdit.setText(_translate("DialogOrgChoose", "Редагувати"))
        self.btnOrgAdd.setToolTip(_translate("DialogOrgChoose", "Додати запис"))
        self.btnOrgCancel.setText(_translate("DialogOrgChoose", "Скасувати"))
        self.btnOrgDelete.setToolTip(_translate("DialogOrgChoose", "Видалити запис"))
        self.labelOrgAddress.setText(_translate("DialogOrgChoose", "Адреса"))
        self.labelOrgName.setText(_translate("DialogOrgChoose", "Назва"))
        self.labelOrgCode.setText(_translate("DialogOrgChoose", "ЄДРПОУ"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("DialogOrgChoose", "Назва підрозділу"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("DialogOrgChoose", "ЄДРПОУ"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("DialogOrgChoose", "Юридична адреса"))

import icons

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogOrgChoose = QtWidgets.QDialog()
    ui = Ui_DialogOrgChoose()
    ui.setupUi(DialogOrgChoose)
    DialogOrgChoose.show()
    sys.exit(app.exec_())
